language: objective-c
 
before_install:
  - gem install cocoapods -v '0.34.4'
  - pod install
 
script:
  - xctool -workspace YOURPROJECT.xcworkspace -scheme YOURSCHEME -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace YOURPROJECT.xcworkspace -scheme YOURSCHEME -destination 'platform=iOS Simulator,name=iPhone 6' test
 
after_success:
  - chmod 755 chatwork.sh
  - ./chatwork.sh
